app.out : main.o menu.o insert.o search.o quit.o delete.o display.o 
	gcc -o app.out main.o menu.o insert.o search.o quit.o delete.o display.o

main.o : main.c mylib.h

insert.o : insert.c mylib.h

search.o : search.c mylib.h

quit.o : quit.c mylib.h

delete.o : delete.c mylib.h

display.o : display.c mylib.h

menu.o : menu.c

  
